### ISSUE TITLE
A question in request.go

### ISSUE THREAD

**Issue by cnjack** [cosiner/zerver#2]
Line 98
```
func (req *request) RemoteIP() string {
	return strings.Split(req.RemoteAddr(), ":")[1]
}
```
The RemoteAddr is 
>127.0.0.1:61119  

and the result RemoteIP() is 61119
is it ture?
or should the mothod be named with RemotePort?

**Comment by cosiner** [comment]
Sorry, it's my mistake.

**Comment by cosiner** [comment]
It should be `strings.Split(req.RemoteAddr(), ":")[0]`

**Comment by cnjack** [comment]
yep
