### ISSUE TITLE
Middleware in zerver

### ISSUE THREAD

**Issue by cnjack** [cosiner/zerver#3]
We can write like negroni,I use it today and feel very good   
the code what I can write with negroni   
```
func (style *MyStyle) ServeHTTP(rw http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
	for k, v := range style.config {
		rw.Header().Set(k, v)
	}
	next(rw, r)
}
```   
and    
```
n := negroni.New(negroni.NewStatic(http.Dir("public")), NewMyStyle)
	n.UseHandler(router)
	n.Run(":8080")
```
it is refined

**Comment by cnjack** [comment]
I can insert my Handler before the router's Handler active without broking the farmwork

**Comment by cnjack** [comment]
It just a tip of advice

**Comment by cnjack** [comment]
The func in negroni called "middleware"

**Comment by cosiner** [comment]
Zerver also provide `Filter/FilterFunc`.
`func filter(req Request, resp Response, chain FilterChain) {
    chain(req, resp)
}
`
You can also use `InterceptHandler(handler HandlerFunc, filters ...Filter) -> HandlerFunc`
and `InterceptHandler2(handler HandlerFunc, filters ...FilterFunc) -> HandlerFunc`.

You can think Filter/FilterFunc as a middleware. Filter(middleware) and Handler is stricly distinguished,
they have different interface, but in negroni, middleware and handler has the same interface
`(rw http.ResponseWriter, r *http.Request, next http.HandlerFunc)`.

May be it's better than zerver, just make your own choice.

**Comment by cosiner** [comment]
I have change the readme, and added some examples.
